# Load dữ liệu

In [ ]:
import pandas as pd
import gdown

# Tải dữ liệu từ Drive
gdown.download("https://drive.google.com/uc?id=1OvzAYICGvUsgJEzCSeCMpJr09t-Glfkn", "users.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=16fZ6YD1RlxITtSEYgu0s3P7zSxpR2hr1", "movies.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=1gVQem4NmIkeEAXHJWGDpSjN6yCfvWXVt", "ratings.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=1qHAhfYmdEZFDxtqw6YRJU4Id5kVcsenh", "user_profiles.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=18gwpCIcdT6hT4ULxmOT8dQIS1nKUClYG", "user_actions.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=18vT1PzFeZ0UCC4DkxtG6mC43_uPTL9v5", "train_ratings_80.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=1k2cDkpQm1x6x6nGQCuXkNivVA2nb0UtB", "test_ratings_20.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=1_z5seijOe5MD93PEJjypE5NsQr8mfz40", "train_ratings_70.csv", quiet=False)
gdown.download("https://drive.google.com/uc?id=1ZXiGET_am5oaevq4ul_vdRRG6yPrRMqq", "test_ratings_30.csv", quiet=False)

# Đọc file csv
users_df = pd.read_csv("users.csv")
movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv")
user_profiles_df = pd.read_csv("user_profiles.csv")
user_actions_df = pd.read_csv("user_actions.csv")
train_ratings_80_df = pd.read_csv("train_ratings_80.csv")
test_ratings_20_df = pd.read_csv("test_ratings_20.csv")
train_ratings_70_df = pd.read_csv("train_ratings_70.csv")
test_ratings_30_df = pd.read_csv("test_ratings_30.csv")

# Xem dữ liệu
print("Users DataFrame Head:")
display(users_df.head())

print("\nMovies DataFrame Head:")
display(movies_df.head())

print("\nRatings DataFrame Head:")
display(ratings_df.head())

print("\nUser profile DataFrame Head:")
display(user_profiles_df.head())

print("\nUser action DataFrame Head:")
display(user_actions_df.head())

print("\nTrain ratings DataFrame Head:")
display(train_ratings_80_df.head())

print("\nTest ratings DataFrame Head:")
display(test_ratings_20_df.head())

print("\nTrain ratings DataFrame Head:")
display(train_ratings_70_df.head())

print("\nTest ratings DataFrame Head:")
display(test_ratings_30_df.head())

Downloading...
From: https://drive.google.com/uc?id=1OvzAYICGvUsgJEzCSeCMpJr09t-Glfkn
To: /content/users.csv
100%|██████████| 215k/215k [00:00<00:00, 3.97MB/s]
Downloading...
From: https://drive.google.com/uc?id=16fZ6YD1RlxITtSEYgu0s3P7zSxpR2hr1
To: /content/movies.csv
100%|██████████| 1.45M/1.45M [00:00<00:00, 11.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1gVQem4NmIkeEAXHJWGDpSjN6yCfvWXVt
To: /content/ratings.csv
100%|██████████| 22.6M/22.6M [00:00<00:00, 68.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1qHAhfYmdEZFDxtqw6YRJU4Id5kVcsenh
To: /content/user_profiles.csv
100%|██████████| 42.7M/42.7M [00:00<00:00, 55.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=18gwpCIcdT6hT4ULxmOT8dQIS1nKUClYG
To: /content/user_actions.csv
100%|██████████| 721/721 [00:00<00:00, 3.53MB/s]
Downloading...
From: https://drive.google.com/uc?id=18vT1PzFeZ0UCC4DkxtG6mC43_uPTL9v5
To: /content/train_ratings_80.csv
100%|██████████| 17.2M/17.2M [00:00<00:00, 55.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1k2cDkpQm1x6x6nGQCuXkNivVA2nb0UtB
To: /content/test_ratings_20.csv
100%|██████████| 4.37M/4.37M [00:00<00:00, 24.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_z5seijOe5MD93PEJjypE5NsQr8mfz40
To: /content/train_ratings_70.csv
100%|██████████| 15.1M/15.1M [00:00<00:00, 37.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZXiGET_am5oaevq4ul_vdRRG6yPrRMqq
To: /content/test_ratings_30.csv
100%|██████████| 6.54M/6.54M [00:00<00:00, 24.8MB/s]

Users DataFrame Head:

   UserID Gender       Age            Occupation Zip-code
0       1      F  Under 18          K-12 student    48067
1       2      M       56+         self-employed    70072
2       3      M     25-34             scientist    55117
3       4      M     45-49  executive/managerial    02460
4       5      M     25-34                writer    55455

Movies DataFrame Head:

,ID,Title,Genres,movieId,tmdbId,Overview,Keyword,Network
0,1,Toy Story (1995),Animation|Children's|Comedy,1.0,862.0,"Led by Woody, Andy's toys live happily in his ...","rescue, friendship, mission, jealousy, villain...",Pixar
1,2,Jumanji (1995),Adventure|Children's|Fantasy,2.0,8844.0,When siblings Judy and Peter discover an encha...,"giant insect, board game, disappearance, jungl...",TriStar Pictures
2,3,Grumpier Old Men (1995),Comedy|Romance,3.0,15602.0,A family wedding reignites the ancient feud be...,"fishing, sequel, old man, best friend, wedding...",Lancaster Gate
3,4,Waiting to Exhale (1995),Comedy|Drama,4.0,31357.0,"Cheated on, mistreated and stepped on, the wom...","based on novel or book, single mother, divorce...",20th Century Fox
4,5,Father of the Bride Part II (1995),Comedy,5.0,11862.0,Just when George Banks has recovered from his ...,"daughter, baby, parent child relationship, mid...",Touchstone Pictures

Ratings DataFrame Head:

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

User profile DataFrame Head:

   UserID  MovieID  ActionID
0       1     1193        10
1       1     1193        13
2       1      661         8
3       1      661        22
4       1      661        29

User action DataFrame Head:

   ID             Name  Weight
0   1       play_movie     1.0
1   2  play_25_percent     1.2
2   3  play_50_percent     1.5
3   4  play_75_percent     2.0
4   5   complete_movie     3.0

Train ratings DataFrame Head:

   UserID  MovieID  Rating  Timestamp
0       1      594       4  978302268
1       1     1097       4  978301953
2       1     1287       5  978302039
3       1     1907       4  978824330
4       1     2355       5  978824291

Test ratings DataFrame Head:

   UserID  MovieID  Rating  Timestamp
0       1     2797       4  978302039
1       1     1961       5  978301590
2       1     1207       4  978300719
3       1     2398       4  978302281
4       1     2692       4  978301570

Train ratings DataFrame Head:

   UserID  MovieID  Rating  Timestamp
0       1     1022       5  978300055
1       1     2340       3  978300103
2       1      260       4  978300760
3       1      588       4  978824268
4       1      531       4  978302149

Test ratings DataFrame Head:

   UserID  MovieID  Rating  Timestamp
0       1     2797       4  978302039
1       1     1961       5  978301590
2       1     1207       4  978300719
3       1     2398       4  978302281
4       1     2692       4  978301570

# Phân tích độ tương quan

In [ ]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("all-MiniLM-L6-v2")
# 2. Load DataFrame movies
movies = movies_df
# Đảm bảo không có NaN
movies = movies.fillna("")
# 3. Encode Title + các cột còn lại
title_vec    = model.encode(movies["Title"].tolist())
genres_vec   = model.encode(movies["Genres"].tolist())
keyword_vec  = model.encode(movies["Keyword"].tolist())
overview_vec = model.encode(movies["Overview"].tolist())
network_vec  = model.encode(movies["Network"].tolist())

# 4. Tính độ tương quan cosine (mean similarity)

corr_genres   = cosine_similarity(title_vec, genres_vec).mean()
corr_keyword  = cosine_similarity(title_vec, keyword_vec).mean()
corr_overview = cosine_similarity(title_vec, overview_vec).mean()
corr_network  = cosine_similarity(title_vec, network_vec).mean()


# 5. Xuất bảng kết quả
result = pd.DataFrame({
    "Feature": ["Genres", "Keyword", "Overview", "Network"],
    "Correlation_with_Title": [
        corr_genres,
        corr_keyword,
        corr_overview,
        corr_network
    ]
})

print(result)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

    Feature  Correlation_with_Title
0    Genres                0.191646
1   Keyword                0.123689
2  Overview                0.104136
3   Network                0.177777

# Content-Based

Tính toán movieVector

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import normalize

# =============================================
# 1️⃣ Load Sentence-BERT model
# =============================================
print("Loading Sentence-BERT model...")
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Model loaded!")

# =============================================
# 2️⃣ Load movies DataFrame
# =============================================
movies = movies_df.copy()

# =============================================
# 3️⃣ Encode từng feature
# =============================================
print("Encoding features...")

title_vec    = model.encode(movies["Title"].fillna("").tolist())
genres_vec   = model.encode(movies["Genres"].fillna("").tolist())
overview_vec = model.encode(movies["Overview"].fillna("").tolist())
keyword_vec  = model.encode(movies["Keyword"].fillna("").tolist())
network_vec  = model.encode(movies["Network"].fillna("").tolist())

print("Encoding done!")

# =============================================
# 4️⃣ Normalize từng vector
# =============================================
title_vec    = normalize(title_vec)
genres_vec   = normalize(genres_vec)
overview_vec = normalize(overview_vec)
keyword_vec  = normalize(keyword_vec)
network_vec  = normalize(network_vec)

# =============================================
# 5️⃣ TRỌNG SỐ
# =============================================
w_title    = 0.41   # ưu tiên Title mạnh nhất
w_genres   = 0.19
w_keyword  = 0.12
w_overview = 0.10
w_network  = 0.18

# Tổng = 1.0 → OK

print("Using weights:")
print("Title:", w_title)
print("Genres:", w_genres)
print("Keyword:", w_keyword)
print("Overview:", w_overview)
print("Network:", w_network)

# =============================================
# 6️⃣ Fuse vector có trọng số
# =============================================
final_movie_vec = (
    title_vec    * w_title +
    genres_vec   * w_genres +
    keyword_vec  * w_keyword +
    overview_vec * w_overview +
    network_vec  * w_network
)

# =============================================
# 7️⃣ Normalize vector cuối
# =============================================
final_movie_vec = normalize(final_movie_vec)

# =============================================
# 8️⃣ Lưu vào DataFrame
# =============================================
movies["movieVector"] = final_movie_vec.tolist()

movies_to_save = movies[["ID", "Title", "movieVector"]].copy()

# =============================================
# 9️⃣ Lưu CSV
# =============================================
movies_to_save.to_csv("movie_vector.csv", index=False)

print("✔️ File movie_vector.csv đã được lưu!")
print(movies_to_save.head())

Loading Sentence-BERT model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model loaded!
Encoding features...
Encoding done!
Using weights:
Title: 0.41
Genres: 0.19
Keyword: 0.12
Overview: 0.1
Network: 0.18
✔️ File movie_vector.csv đã được lưu!
   ID                               Title  \
0   1                    Toy Story (1995)
1   2                      Jumanji (1995)
2   3             Grumpier Old Men (1995)
3   4            Waiting to Exhale (1995)
4   5  Father of the Bride Part II (1995)

                                         movieVector
0  [-0.09052827209234238, 0.010638929903507233, 0...
1  [-0.0710516944527626, 0.1324291229248047, -0.0...
2  [-0.09972634166479111, 0.0013706883182749152, ...
3  [-0.07287830114364624, -0.0072005558758974075,...
4  [-0.07940741628408432, -0.006598162930458784, ...

Tính toán userProfileVector

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize
from tqdm import tqdm  # tiến trình để theo dõi

# =============================================
# 1️⃣ Load data
# =============================================

# Merge user_profile với action để lấy Weight
df = user_profiles_df.merge(user_actions_df, left_on="ActionID", right_on="ID", how="left")

# =============================================
# 2️⃣ Tạo dict lookup nhanh cho movieVector
# =============================================
movie_vector_dict = dict(zip(movies["ID"], movies["movieVector"]))

# =============================================
# 3️⃣ Group theo UserID
# =============================================
user_vectors_list = []

print("Calculating user vectors for all users...")
for uid, user_data in tqdm(df.groupby("UserID"), total=df["UserID"].nunique()):
    weighted_vectors = []
    weights = []

    for _, row in user_data.iterrows():
        movie_vec = movie_vector_dict.get(row["MovieID"])
        if movie_vec is None:
            continue

        movie_vec = np.array(movie_vec)
        w = row["Weight"]
        weighted_vectors.append(movie_vec * w)
        weights.append(w)

    if len(weighted_vectors) == 0:
        continue

    # Tính trung bình có trọng số
    user_vec = np.sum(weighted_vectors, axis=0) / sum(weights)

    # Normalize vector cuối cùng
    user_vec = normalize(user_vec.reshape(1, -1))[0]

    user_vectors_list.append({
        "UserID": uid,
        "userVector": user_vec.tolist()  # lưu dưới dạng list để CSV
    })

# =============================================
# 4️⃣ Lưu vào CSV
# =============================================
user_vectors_df = pd.DataFrame(user_vectors_list)
user_vectors_df.to_csv("user_profile_vector.csv", index=False)

print("✔️ File user_profile_vector.csv đã được lưu!")
print(user_vectors_df.head())

Calculating user vectors for all users...

100%|██████████| 6040/6040 [04:19<00:00, 23.25it/s]

✔️ File user_profile_vector.csv đã được lưu!
   UserID                                         userVector
0       1  [-0.06285085072320101, 0.0003511591570739866, ...
1       2  [-0.07523755870355883, -0.0015332619589268914,...
2       3  [-0.07140718609726425, 0.009765766633572393, -...
3       4  [-0.06879509777068744, -0.007361140738783501, ...
4       5  [-0.0856652314450893, -0.022213968434980653, -...

Chạy và đánh giá các thuật toán (Theo User profile vector và Movie vector)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

# =============================
# 1️⃣ Load data
# =============================
movies = pd.read_csv("movie_vector.csv")
user_vectors_df = pd.read_csv("user_profile_vector.csv")
user_profile = pd.read_csv("user_profiles.csv")
user_action = pd.read_csv("user_actions.csv")

movies['movieVector'] = movies['movieVector'].apply(lambda x: np.array(eval(x)))
user_vectors_df['userVector'] = user_vectors_df['userVector'].apply(lambda x: np.array(eval(x)))

df = user_profile.merge(user_action, left_on='ActionID', right_on='ID', how='left')
RELEVANT_THRESHOLD = 2.0

def relevant_movies(user_id):
    data = df[df['UserID']==user_id]
    rel = data[data['Weight']>=RELEVANT_THRESHOLD]['MovieID'].unique()
    return set(rel)

# =============================
# 2️⃣ Modify vector by ratio
# =============================
def apply_ratio(movie_vecs, user_vec, wm, wu):
    return movie_vecs * wm, user_vec * wu

# =============================
# 3️⃣ Recommendation
# =============================
def recommend_movies(user_id, wm, wu, method='cosine', top_n=10):
    uvec = user_vectors_df.loc[user_vectors_df['UserID']==user_id,'userVector'].values[0]
    mvecs = np.stack(movies['movieVector'].values)

    mvecs, uvec = apply_ratio(mvecs, uvec, wm, wu)
    uvec = uvec.reshape(1, -1)

    if method=='cosine':
        sims = cosine_similarity(uvec, mvecs)[0]
    elif method=='pearson':
        sims = np.array([np.corrcoef(uvec.flatten(), mv.flatten())[0,1] for mv in mvecs])
        sims = np.nan_to_num(sims)
    elif method=='jaccard':
        ub = (uvec>0).astype(int)
        mb = (mvecs>0).astype(int)
        sims = np.array([np.sum(np.minimum(ub, mv)) / np.sum(np.maximum(ub, mv)) for mv in mb])
    elif method=='manhattan':
        sims = -np.sum(np.abs(mvecs - uvec), axis=1)

    movies['sim'] = sims
    return movies.sort_values('sim', ascending=False).head(top_n)[['ID','Title','sim']]

# =============================
# 4️⃣ Ranking metrics
# =============================
def precision_at_n(user_id, recs, n=10):
    relevant = relevant_movies(user_id)
    rec_ids = recs['ID'].head(n).tolist()
    return len(set(rec_ids) & relevant) / n

def recall_at_n(user_id, recs, n=10):
    relevant = relevant_movies(user_id)
    if len(relevant)==0:
        return np.nan
    rec_ids = recs['ID'].head(n).tolist()
    return len(set(rec_ids) & relevant) / len(relevant)

def f1_at_n(user_id, recs, n=10):
    p = precision_at_n(user_id, recs, n)
    r = recall_at_n(user_id, recs, n)
    return 2*p*r/(p+r) if (p+r)>0 else 0

def ndcg_at_n(user_id, recs, n=10):
    relevant = relevant_movies(user_id)
    rec_ids = recs['ID'].head(n).tolist()
    dcg = sum([1/np.log2(i+2) for i, mid in enumerate(rec_ids) if mid in relevant])
    ideal = sum([1/np.log2(i+2) for i in range(min(len(relevant), n))])
    return dcg/ideal if ideal>0 else 0

# =============================
# 5️⃣ Step 1: Chọn similarity method
# =============================
wm_default, wu_default = 0.5, 0.5
methods = ['cosine','pearson','jaccard','manhattan']
results_step1 = []

for method in methods:
    print(f"Testing method={method} with wm={wm_default}, wu={wu_default}")
    Ps, Rs, F1s, NDCGs = [], [], [], []
    for uid in tqdm(user_vectors_df['UserID']):
        recs = recommend_movies(uid, wm_default, wu_default, method=method)
        Ps.append(precision_at_n(uid, recs))
        Rs.append(recall_at_n(uid, recs))
        F1s.append(f1_at_n(uid, recs))
        NDCGs.append(ndcg_at_n(uid, recs))
    results_step1.append({
        "method": method,
        "precision@10": np.nanmean(Ps),
        "recall@10": np.nanmean(Rs),
        "f1@10": np.nanmean(F1s),
        "ndcg@10": np.nanmean(NDCGs)
    })

results_step1_df = pd.DataFrame(results_step1)
print("\nStep 1 results:")
print(results_step1_df)

best_method = results_step1_df.sort_values('precision@10', ascending=False)['method'].iloc[0]
print(f"Best similarity method: {best_method}")

# =============================
# 6️⃣ Step 2: Tối ưu wm/wu ratio
# =============================
ratios = [(0.2,0.8),(0.3,0.7),(0.4,0.6),(0.5,0.5),(0.6,0.4),(0.7,0.3),(0.8,0.2)]
results_step2 = []

for wm, wu in ratios:
    print(f"Testing ratio wm={wm}, wu={wu} with method={best_method}")
    Ps, Rs, F1s, NDCGs = [], [], [], []
    for uid in tqdm(user_vectors_df['UserID']):
        recs = recommend_movies(uid, wm, wu, method=best_method)
        Ps.append(precision_at_n(uid, recs))
        Rs.append(recall_at_n(uid, recs))
        F1s.append(f1_at_n(uid, recs))
        NDCGs.append(ndcg_at_n(uid, recs))
    results_step2.append({
        "wm": wm,
        "wu": wu,
        "precision@10": np.nanmean(Ps),
        "recall@10": np.nanmean(Rs),
        "f1@10": np.nanmean(F1s),
        "ndcg@10": np.nanmean(NDCGs)
    })

results_step2_df = pd.DataFrame(results_step2)
print("\nStep 2 results (wm/wu tuning):")
print(results_step2_df)

best_ratio = results_step2_df.sort_values('precision@10', ascending=False).iloc[0]
print(f"Best wm/wu ratio: wm={best_ratio['wm']}, wu={best_ratio['wu']}")

Testing method=cosine with wm=0.5, wu=0.5

100%|██████████| 6040/6040 [07:35<00:00, 13.26it/s]

Testing method=pearson with wm=0.5, wu=0.5

100%|██████████| 6040/6040 [27:57<00:00,  3.60it/s]

Testing method=jaccard with wm=0.5, wu=0.5

100%|██████████| 6040/6040 [08:38<00:00, 11.65it/s]

Testing method=manhattan with wm=0.5, wu=0.5

100%|██████████| 6040/6040 [05:03<00:00, 19.91it/s]

Step 1 results:
      method  precision@10  recall@10     f1@10   ndcg@10
0     cosine      0.195712   0.036960  0.056053  0.203093
1    pearson      0.195861   0.036965  0.056066  0.203244
2    jaccard      0.149123   0.023794  0.036932  0.150729
3  manhattan      0.197583   0.036298  0.055195  0.207934
Best similarity method: manhattan
Testing ratio wm=0.2, wu=0.8 with method=manhattan

100%|██████████| 6040/6040 [05:04<00:00, 19.86it/s]

Testing ratio wm=0.3, wu=0.7 with method=manhattan

100%|██████████| 6040/6040 [05:03<00:00, 19.90it/s]

Testing ratio wm=0.4, wu=0.6 with method=manhattan

100%|██████████| 6040/6040 [05:02<00:00, 20.00it/s]

Testing ratio wm=0.5, wu=0.5 with method=manhattan

100%|██████████| 6040/6040 [05:02<00:00, 20.00it/s]

Testing ratio wm=0.6, wu=0.4 with method=manhattan

100%|██████████| 6040/6040 [05:01<00:00, 20.02it/s]

Testing ratio wm=0.7, wu=0.3 with method=manhattan

100%|██████████| 6040/6040 [05:00<00:00, 20.08it/s]

Testing ratio wm=0.8, wu=0.2 with method=manhattan

100%|██████████| 6040/6040 [05:01<00:00, 20.03it/s]

Step 2 results (wm/wu tuning):
    wm   wu  precision@10  recall@10     f1@10   ndcg@10
0  0.2  0.8      0.206474   0.035051  0.053838  0.229455
1  0.3  0.7      0.210629   0.036625  0.056030  0.234812
2  0.4  0.6      0.207583   0.037094  0.056535  0.225853
3  0.5  0.5      0.197583   0.036298  0.055195  0.207934
4  0.6  0.4      0.183030   0.034315  0.052036  0.188268
5  0.7  0.3      0.148162   0.027487  0.041513  0.155751
6  0.8  0.2      0.128129   0.018965  0.029463  0.132133
Best wm/wu ratio: wm=0.3, wu=0.7

Chạy và đánh giá các thuật toán (Theo Movie vector)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# =============================
# 1️⃣ Load dữ liệu
# =============================
movie_vecs_df = pd.read_csv("movie_vector.csv")  # ID, Title, movieVector
movie_vecs_df['movieVector'] = movie_vecs_df['movieVector'].apply(lambda x: np.array(eval(x)))

movies_meta = pd.read_csv("movies.csv")  # ID, Title, Genres
movies_meta['GenresSet'] = movies_meta['Genres'].apply(lambda x: set(x.split('|')) if isinstance(x, str) else set())

# map movie_id -> genres set
movieid_to_genres = movies_meta.set_index('ID')['GenresSet'].to_dict()

movie_vecs = np.stack(movie_vecs_df['movieVector'].values)
movie_ids = movie_vecs_df['ID'].values

# =============================
# 2️⃣ Hàm tính similarity
# =============================
def compute_similarity(vecs, method='cosine'):
    if method == 'cosine':
        return cosine_similarity(vecs)

    elif method == 'pearson':
        sims = np.corrcoef(vecs)
        return np.nan_to_num(sims)

    elif method == 'manhattan':
        n = vecs.shape[0]
        sims = np.zeros((n, n))
        for i in range(n):
            sims[i] = -np.sum(np.abs(vecs - vecs[i]), axis=1)
        return sims

    elif method == 'jaccard':
        bin_vecs = (vecs > 0).astype(int)
        n = vecs.shape[0]
        sims = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                inter = np.sum(np.minimum(bin_vecs[i], bin_vecs[j]))
                union = np.sum(np.maximum(bin_vecs[i], bin_vecs[j]))
                sims[i][j] = inter / union if union > 0 else 0
        return sims

    else:
        raise ValueError("Unknown similarity method")

# =============================
# 3️⃣ Recommend phim tương tự
# =============================
def recommend_similar_movies(movie_id, similarity_matrix, top_n=10):
    idx = np.where(movie_ids == movie_id)[0][0]
    sims = similarity_matrix[idx].copy()
    sims[idx] = -1  # loại bỏ chính phim
    top_idx = np.argsort(sims)[::-1][:top_n]
    top_movie_ids = movie_ids[top_idx]
    return top_movie_ids

# =============================
# 4️⃣ Evaluation
# =============================
def evaluate_similarity_metrics(method, top_n=10):
    sim_matrix = compute_similarity(movie_vecs, method)

    precision_list, recall_list, ndcg_list = [], [], []

    for mid in movie_ids:
        true_genres = movieid_to_genres[mid]

        # danh sách phim được gợi ý
        rec_ids = recommend_similar_movies(mid, sim_matrix, top_n)

        # phim nào là relevant (cùng ít nhất 1 genre)
        relevant_movies = [
            other for other in movie_ids
            if other != mid and len(movieid_to_genres[other] & true_genres) > 0
        ]

        num_relevant = len(relevant_movies)

        # ================================
        # Precision & Recall
        # ================================
        hits = sum([len(movieid_to_genres[rid] & true_genres) > 0 for rid in rec_ids])

        precision_list.append(hits / top_n)
        recall_list.append(hits / num_relevant if num_relevant > 0 else 0)

        # ================================
        # NDCG
        # ================================
        dcg = 0
        for rank, rid in enumerate(rec_ids):
            if len(movieid_to_genres[rid] & true_genres) > 0:
                dcg += 1 / np.log2(rank + 2)

        ideal_hits = min(num_relevant, top_n)
        idcg = sum([1 / np.log2(i + 2) for i in range(ideal_hits)])

        ndcg_list.append(dcg / idcg if idcg > 0 else 0)

    precision = np.mean(precision_list)
    recall = np.mean(recall_list)
    f1 = 2 * precision * recall / (precision + recall) if precision + recall > 0 else 0
    ndcg = np.mean(ndcg_list)

    return precision, recall, f1, ndcg

# =============================
# 5️⃣ So sánh các phương pháp
# =============================
methods = ['cosine', 'pearson', 'manhattan', 'jaccard']
results = {}

for method in methods:
    precision, recall, f1, ndcg = evaluate_similarity_metrics(method, top_n=10)
    results[method] = precision
    print(f"{method}: Precision@10={precision:.4f}, Recall@10={recall:.4f}, F1@10={f1:.4f}, NDCG@10={ndcg:.4f}")

best_method = max(results, key=results.get)
print(f"\n🔥 Best similarity method based on Precision@10: {best_method}")

cosine: Precision@10=0.8422, Recall@10=0.0142, F1@10=0.0280, NDCG@10=0.8487
pearson: Precision@10=0.8421, Recall@10=0.0142, F1@10=0.0280, NDCG@10=0.8486
manhattan: Precision@10=0.8592, Recall@10=0.0147, F1@10=0.0289, NDCG@10=0.8805
jaccard: Precision@10=0.7851, Recall@10=0.0123, F1@10=0.0243, NDCG@10=0.7958

🔥 Best similarity method based on Precision@10: manhattan

# Collaborative

User-based CF và Item-based CF theo bảng Ratings

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_squared_error, precision_score, recall_score, f1_score
from tqdm import tqdm


# 1️⃣ Hàm làm sạch similarity

def clean_similarity(sim):
    sim = np.nan_to_num(sim, nan=0.0, posinf=0.0, neginf=0.0)
    np.fill_diagonal(sim, 1.0)
    sim = np.clip(sim, 0, 1)
    return sim



# 2️⃣ Hàm tính similarity

def user_similarity(matrix, method='cosine'):
    if method == 'cosine':
        sim = cosine_similarity(matrix)

    elif method == 'pearson':
        sim = matrix.T.corr().values

    elif method == 'adjusted_cosine':
        matrix_adj = matrix - matrix.mean(axis=1).values.reshape(-1, 1)
        sim = cosine_similarity(matrix_adj)

    sim = clean_similarity(sim)
    return pd.DataFrame(sim, index=matrix.index, columns=matrix.index)


def item_similarity(matrix, method='cosine'):
    if method == 'cosine':
        sim = cosine_similarity(matrix.T)

    elif method == 'pearson':
        sim = matrix.corr().values

    elif method == 'adjusted_cosine':
        matrix_adj = matrix - matrix.mean(axis=1).values.reshape(-1, 1)
        sim = cosine_similarity(matrix_adj.T)

    sim = clean_similarity(sim)
    return pd.DataFrame(sim, index=matrix.columns, columns=matrix.columns)



# 3️⃣ Predict an toàn
#
def predict_user(user_id, movie_id, user_sim, matrix):
    if user_id not in matrix.index or movie_id not in matrix.columns:
        return np.nan

    sim_scores = user_sim.loc[user_id].values
    ratings = matrix[movie_id].values

    mask = ratings > 0
    if mask.sum() == 0:
        return np.nan

    w = sim_scores[mask]
    if w.sum() == 0:
        return np.nan

    return np.dot(w, ratings[mask]) / w.sum()


def predict_item(user_id, movie_id, item_sim, matrix):
    if user_id not in matrix.index or movie_id not in matrix.columns:
        return np.nan

    sim_scores = item_sim.loc[movie_id].values
    ratings = matrix.loc[user_id].values

    mask = ratings > 0
    if mask.sum() == 0:
        return np.nan

    w = sim_scores[mask]
    if w.sum() == 0:
        return np.nan

    return np.dot(w, ratings[mask]) / w.sum()

# 4️⃣ Evaluation + Precision, Recall, F1

def evaluate_CF_full(train_ratings, test_ratings, label="NoLabel", threshold=3):
    print(f"\n======== KẾT QUẢ: {label} ========")

    train_matrix = train_ratings.pivot(index='UserID', columns='MovieID', values='Rating').fillna(0)
    sim_methods = ['cosine', 'adjusted_cosine', 'pearson']

    # ========================================
    # USER-BASED CF
    # ========================================
    for method in sim_methods:
        print(f"\n--- UserBased-{method}: Tính similarity... ---")
        user_sim = user_similarity(train_matrix, method)

        y_true, y_pred = [], []

        print(f"--- UserBased-{method}: Predict test set ---")
        for row in tqdm(test_ratings.itertuples(), total=len(test_ratings), desc=f"Predicting {method}"):
            pred = predict_user(row.UserID, row.MovieID, user_sim, train_matrix)
            if not np.isnan(pred):
                y_true.append(row.Rating)
                y_pred.append(pred)

        if len(y_true) > 0:
            rmse = np.sqrt(mean_squared_error(y_true, y_pred))
            y_true_bin = [1 if r >= threshold else 0 for r in y_true]
            y_pred_bin = [1 if r >= threshold else 0 for r in y_pred]
            precision = precision_score(y_true_bin, y_pred_bin)
            recall = recall_score(y_true_bin, y_pred_bin)
            f1 = f1_score(y_true_bin, y_pred_bin)
        else:
            rmse = precision = recall = f1 = np.nan

        print(f"UserBased-{method}: RMSE={rmse:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")

    # ITEM-BASED CF

    for method in sim_methods:
        print(f"\n--- ItemBased-{method}: Tính similarity... ---")
        item_sim = item_similarity(train_matrix, method)

        y_true, y_pred = [], []

        print(f"--- ItemBased-{method}: Predict test set ---")
        for row in tqdm(test_ratings.itertuples(), total=len(test_ratings), desc=f"Predicting {method}"):
            pred = predict_item(row.UserID, row.MovieID, item_sim, train_matrix)
            if not np.isnan(pred):
                y_true.append(row.Rating)
                y_pred.append(pred)

        if len(y_true) > 0:
            rmse = np.sqrt(mean_squared_error(y_true, y_pred))
            y_true_bin = [1 if r >= threshold else 0 for r in y_true]
            y_pred_bin = [1 if r >= threshold else 0 for r in y_pred]
            precision = precision_score(y_true_bin, y_pred_bin)
            recall = recall_score(y_true_bin, y_pred_bin)
            f1 = f1_score(y_true_bin, y_pred_bin)
        else:
            rmse = precision = recall = f1 = np.nan

        print(f"ItemBased-{method}: RMSE={rmse:.4f}, Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")


# 5️⃣ Chạy ví dụ

train_80 = pd.read_csv("train_ratings_80.csv")
test_20 = pd.read_csv("test_ratings_20.csv")
evaluate_CF_full(train_80, test_20, label="Train 80 / Test 20")

train_70 = pd.read_csv("train_ratings_70.csv")
test_30 = pd.read_csv("test_ratings_30.csv")
evaluate_CF_full(train_70, test_30, label="Train 70 / Test 30")

======== KẾT QUẢ: Train 80 / Test 20 ========

--- UserBased-cosine: Tính similarity... ---
--- UserBased-cosine: Predict test set ---

Predicting cosine: 100%|██████████| 202451/202451 [00:43<00:00, 4703.40it/s]

UserBased-cosine: RMSE=0.9737, Precision=0.8860, Recall=0.9056, F1=0.8957

--- UserBased-adjusted_cosine: Tính similarity... ---
--- UserBased-adjusted_cosine: Predict test set ---

Predicting adjusted_cosine: 100%|██████████| 202451/202451 [00:42<00:00, 4806.49it/s]

UserBased-adjusted_cosine: RMSE=0.9713, Precision=0.8864, Recall=0.9066, F1=0.8964

--- UserBased-pearson: Tính similarity... ---
--- UserBased-pearson: Predict test set ---

Predicting pearson: 100%|██████████| 202451/202451 [00:41<00:00, 4829.70it/s]

UserBased-pearson: RMSE=0.9713, Precision=0.8864, Recall=0.9066, F1=0.8964

--- ItemBased-cosine: Tính similarity... ---
--- ItemBased-cosine: Predict test set ---

Predicting cosine: 100%|██████████| 202451/202451 [00:20<00:00, 9757.00it/s]

ItemBased-cosine: RMSE=1.0034, Precision=0.8662, Recall=0.9526, F1=0.9073

--- ItemBased-adjusted_cosine: Tính similarity... ---
--- ItemBased-adjusted_cosine: Predict test set ---

Predicting adjusted_cosine: 100%|██████████| 202451/202451 [00:20<00:00, 9735.80it/s]

ItemBased-adjusted_cosine: RMSE=0.9431, Precision=0.8883, Recall=0.9332, F1=0.9102

--- ItemBased-pearson: Tính similarity... ---
--- ItemBased-pearson: Predict test set ---

Predicting pearson: 100%|██████████| 202451/202451 [00:21<00:00, 9584.63it/s]

ItemBased-pearson: RMSE=0.9826, Precision=0.8730, Recall=0.9446, F1=0.9074

======== KẾT QUẢ: Train 70 / Test 30 ========

--- UserBased-cosine: Tính similarity... ---
--- UserBased-cosine: Predict test set ---

Predicting cosine: 100%|██████████| 302774/302774 [01:05<00:00, 4655.63it/s]

UserBased-cosine: RMSE=0.9744, Precision=0.8860, Recall=0.9057, F1=0.8958

--- UserBased-adjusted_cosine: Tính similarity... ---
--- UserBased-adjusted_cosine: Predict test set ---

Predicting adjusted_cosine: 100%|██████████| 302774/302774 [01:04<00:00, 4687.41it/s]

UserBased-adjusted_cosine: RMSE=0.9720, Precision=0.8863, Recall=0.9068, F1=0.8965

--- UserBased-pearson: Tính similarity... ---
--- UserBased-pearson: Predict test set ---

Predicting pearson: 100%|██████████| 302774/302774 [01:03<00:00, 4770.51it/s]

UserBased-pearson: RMSE=0.9720, Precision=0.8863, Recall=0.9068, F1=0.8964

--- ItemBased-cosine: Tính similarity... ---
--- ItemBased-cosine: Predict test set ---

Predicting cosine: 100%|██████████| 302774/302774 [00:30<00:00, 10013.88it/s]

ItemBased-cosine: RMSE=1.0047, Precision=0.8664, Recall=0.9513, F1=0.9069

--- ItemBased-adjusted_cosine: Tính similarity... ---
--- ItemBased-adjusted_cosine: Predict test set ---

Predicting adjusted_cosine: 100%|██████████| 302774/302774 [00:30<00:00, 9829.90it/s]

ItemBased-adjusted_cosine: RMSE=0.9450, Precision=0.8884, Recall=0.9322, F1=0.9098

--- ItemBased-pearson: Tính similarity... ---
--- ItemBased-pearson: Predict test set ---

Predicting pearson: 100%|██████████| 302774/302774 [00:30<00:00, 10085.81it/s]

ItemBased-pearson: RMSE=0.9840, Precision=0.8732, Recall=0.9431, F1=0.9068

Cải tiến Collaborative

Thêm Top-K

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import precision_score, recall_score, f1_score
from tqdm import tqdm


# 1️⃣ Hàm làm sạch similarity

def clean_similarity(sim):
    sim = np.nan_to_num(sim, nan=0.0, posinf=0.0, neginf=0.0)
    np.fill_diagonal(sim, 1.0)
    sim = np.clip(sim, 0, 1)
    return sim


# 2️⃣ Hàm tính similarity

def user_similarity(matrix):
    # adjusted-cosine: trừ trung bình user
    matrix_adj = matrix - matrix.mean(axis=1).values.reshape(-1, 1)
    sim = cosine_similarity(matrix_adj)
    sim = clean_similarity(sim)
    return pd.DataFrame(sim, index=matrix.index, columns=matrix.index)

def item_similarity(matrix):
    # adjusted-cosine: trừ trung bình user
    matrix_adj = matrix - matrix.mean(axis=1).values.reshape(-1, 1)
    sim = cosine_similarity(matrix_adj.T)
    sim = clean_similarity(sim)
    return pd.DataFrame(sim, index=matrix.columns, columns=matrix.columns)

# 3️⃣ Predict an toàn

def predict_user(user_id, movie_id, user_sim, matrix, top_k=None):
    if user_id not in matrix.index or movie_id not in matrix.columns:
        return np.nan

    sim_scores = user_sim.loc[user_id].values
    ratings = matrix[movie_id].values

    mask = ratings > 0
    if mask.sum() == 0:
        return np.nan

    if top_k is not None:
        top_idx = np.argsort(sim_scores[mask])[-top_k:]
        mask_indices = np.where(mask)[0][top_idx]
        w = sim_scores[mask_indices]
        r = ratings[mask_indices]
    else:
        w = sim_scores[mask]
        r = ratings[mask]

    if w.sum() == 0:
        return np.nan

    return np.dot(w, r) / w.sum()

def predict_item(user_id, movie_id, item_sim, matrix, top_k=None):
    if user_id not in matrix.index or movie_id not in matrix.columns:
        return np.nan

    sim_scores = item_sim.loc[movie_id].values
    ratings = matrix.loc[user_id].values

    mask = ratings > 0
    if mask.sum() == 0:
        return np.nan

    if top_k is not None:
        top_idx = np.argsort(sim_scores[mask])[-top_k:]
        mask_indices = np.where(mask)[0][top_idx]
        w = sim_scores[mask_indices]
        r = ratings[mask_indices]
    else:
        w = sim_scores[mask]
        r = ratings[mask]

    if w.sum() == 0:
        return np.nan

    return np.dot(w, r) / w.sum()


# 4️⃣ Evaluation + Precision, Recall, F1 cho top-k

def evaluate_CF_topk(train_ratings, test_ratings, top_k_list=[10, 20, 50], threshold=3):
    print(f"\n======== KẾT QUẢ: Train 80 / Test 20, adjusted-cosine ========")
    train_matrix = train_ratings.pivot(index='UserID', columns='MovieID', values='Rating').fillna(0)

    # ================= User-based =================
    print("\n--- User-Based CF: Tính similarity... ---")
    user_sim = user_similarity(train_matrix)

    for k in top_k_list:
        print(f"\nUser-Based CF Top-{k}: Predict test set")
        y_true, y_pred = [], []
        for row in tqdm(test_ratings.itertuples(), total=len(test_ratings)):
            pred = predict_user(row.UserID, row.MovieID, user_sim, train_matrix, top_k=k)
            if not np.isnan(pred):
                y_true.append(row.Rating)
                y_pred.append(pred)

        if len(y_true) > 0:
            y_true_bin = [1 if r >= threshold else 0 for r in y_true]
            y_pred_bin = [1 if r >= threshold else 0 for r in y_pred]
            precision = precision_score(y_true_bin, y_pred_bin)
            recall = recall_score(y_true_bin, y_pred_bin)
            f1 = f1_score(y_true_bin, y_pred_bin)
        else:
            precision = recall = f1 = np.nan

        print(f"User-Based Top-{k}: Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")

    # ================= Item-based =================
    print("\n--- Item-Based CF: Tính similarity... ---")
    item_sim = item_similarity(train_matrix)

    for k in top_k_list:
        print(f"\nItem-Based CF Top-{k}: Predict test set")
        y_true, y_pred = [], []
        for row in tqdm(test_ratings.itertuples(), total=len(test_ratings)):
            pred = predict_item(row.UserID, row.MovieID, item_sim, train_matrix, top_k=k)
            if not np.isnan(pred):
                y_true.append(row.Rating)
                y_pred.append(pred)

        if len(y_true) > 0:
            y_true_bin = [1 if r >= threshold else 0 for r in y_true]
            y_pred_bin = [1 if r >= threshold else 0 for r in y_pred]
            precision = precision_score(y_true_bin, y_pred_bin)
            recall = recall_score(y_true_bin, y_pred_bin)
            f1 = f1_score(y_true_bin, y_pred_bin)
        else:
            precision = recall = f1 = np.nan

        print(f"Item-Based Top-{k}: Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")

# 5️⃣ Chạy ví dụ
train_80 = pd.read_csv("train_ratings_80.csv")
test_20 = pd.read_csv("test_ratings_20.csv")
evaluate_CF_topk(train_80, test_20)

======== KẾT QUẢ: Train 80 / Test 20, adjusted-cosine ========

--- User-Based CF: Tính similarity... ---

User-Based CF Top-10: Predict test set

100%|██████████| 202451/202451 [01:16<00:00, 2658.31it/s]

User-Based Top-10: Precision=0.8945, Recall=0.8702, F1=0.8822

User-Based CF Top-20: Predict test set

100%|██████████| 202451/202451 [01:06<00:00, 3034.49it/s]

User-Based Top-20: Precision=0.8942, Recall=0.8841, F1=0.8891

User-Based CF Top-50: Predict test set

100%|██████████| 202451/202451 [01:05<00:00, 3081.11it/s]

User-Based Top-50: Precision=0.8924, Recall=0.8941, F1=0.8933

--- Item-Based CF: Tính similarity... ---

Item-Based CF Top-10: Predict test set

100%|██████████| 202451/202451 [00:32<00:00, 6189.23it/s]

Item-Based Top-10: Precision=0.9023, Recall=0.9039, F1=0.9031

Item-Based CF Top-20: Predict test set

100%|██████████| 202451/202451 [00:32<00:00, 6241.11it/s]

Item-Based Top-20: Precision=0.8990, Recall=0.9168, F1=0.9078

Item-Based CF Top-50: Predict test set

100%|██████████| 202451/202451 [00:32<00:00, 6233.36it/s]

Item-Based Top-50: Precision=0.8937, Recall=0.9276, F1=0.9103

Matrix Factorization / SVD

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import precision_score, recall_score, f1_score
from tqdm import tqdm


# 1️⃣ SVD-based CF Top-10

def svd_CF_top10(train_ratings, test_ratings, threshold=3, n_factors=20):
    print(f"\n======== KẾT QUẢ: SVD-CF Top-10, n_factors={n_factors} ========")

    # 1️⃣ Chuyển train thành ma trận user-item
    train_matrix = train_ratings.pivot(index='UserID', columns='MovieID', values='Rating').fillna(0)
    matrix_values = train_matrix.values

    # 2️⃣ Fit SVD
    print("\nFitting TruncatedSVD...")
    svd = TruncatedSVD(n_components=n_factors, random_state=42)
    user_factors = svd.fit_transform(matrix_values)
    item_factors = svd.components_.T
    reconstructed = np.dot(user_factors, item_factors.T)  # ma trận dự đoán

    reconstructed_df = pd.DataFrame(reconstructed, index=train_matrix.index, columns=train_matrix.columns)

    # 3️⃣ Dự đoán Top-10 và đánh giá
    k = 10
    print(f"\nPredict test set using Top-{k} recommendations...")
    y_true, y_pred = [], []

    for row in tqdm(test_ratings.itertuples(), total=len(test_ratings)):
        user_id, movie_id = row.UserID, row.MovieID
        if user_id in reconstructed_df.index and movie_id in reconstructed_df.columns:
            # Lấy top-10 movies dự đoán cao nhất của user
            top_movies = reconstructed_df.loc[user_id].sort_values(ascending=False)[:k]
            if movie_id in top_movies.index:
                y_true.append(row.Rating)
                y_pred.append(reconstructed_df.loc[user_id, movie_id])

    # 4️⃣ Tính Precision, Recall, F1
    if len(y_true) > 0:
        y_true_bin = [1 if r >= threshold else 0 for r in y_true]
        y_pred_bin = [1 if r >= threshold else 0 for r in y_pred]
        precision = precision_score(y_true_bin, y_pred_bin)
        recall = recall_score(y_true_bin, y_pred_bin)
        f1 = f1_score(y_true_bin, y_pred_bin)
    else:
        precision = recall = f1 = np.nan

    print(f"SVD Top-{k}: Precision={precision:.4f}, Recall={recall:.4f}, F1={f1:.4f}")

# =====================================================
# 2️⃣ Chạy thử SVD Top-10
# =====================================================
train_80 = pd.read_csv("train_ratings_80.csv")
test_20 = pd.read_csv("test_ratings_20.csv")

svd_CF_top10(train_80, test_20, threshold=3, n_factors=20)

======== KẾT QUẢ: SVD-CF Top-10, n_factors=20 ========

Fitting TruncatedSVD...

Predict test set using Top-10 recommendations...

100%|██████████| 202451/202451 [01:34<00:00, 2151.14it/s]

SVD Top-10: Precision=0.9849, Recall=0.4213, F1=0.5902

User-based CF và Item-based CF theo bảng User profile

# Hybrid

Content-Based (Item-Item) + Collaborative (Ratings)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity
import pickle
from tqdm import tqdm

# ==============================
# 1️⃣ Load dữ liệu
# ==============================
# Movie vectors (Content-Based)
movie_vecs_df = pd.read_csv("movie_vector.csv")  # ID, Title, movieVector
movie_vecs_df['movieVector'] = movie_vecs_df['movieVector'].apply(lambda x: np.array(eval(x)))
movie_vectors = np.stack(movie_vecs_df['movieVector'].values)
movie_ids = movie_vecs_df['ID'].values
movieid_to_index = {mid: idx for idx, mid in enumerate(movie_ids)}

# Ratings (Collaborative Filtering)
train_df = pd.read_csv("train_ratings_80.csv")
user_item_matrix = train_df.pivot(index='UserID', columns='MovieID', values='Rating').fillna(0)

# ==============================
# 2️⃣ Content-Based: cosine similarity
# ==============================
cb_sim_matrix = cosine_similarity(movie_vectors)

# ==============================
# 3️⃣ Collaborative Filtering: adjusted-cosine
# ==============================
def clean_similarity(sim):
    sim = np.nan_to_num(sim, nan=0.0)
    np.fill_diagonal(sim, 1.0)
    return np.clip(sim, 0, 1)

# User-based similarity
user_mean = user_item_matrix.mean(axis=1).values.reshape(-1,1)
user_adj_matrix = user_item_matrix - user_mean
user_sim = cosine_similarity(user_adj_matrix)
user_sim = clean_similarity(user_sim)
user_sim = pd.DataFrame(user_sim, index=user_item_matrix.index, columns=user_item_matrix.index)

# Item-based similarity
item_mean = user_item_matrix.mean(axis=1).values.reshape(-1,1)
item_adj_matrix = user_item_matrix - item_mean
item_sim = cosine_similarity(item_adj_matrix.T)
item_sim = clean_similarity(item_sim)
item_sim = pd.DataFrame(item_sim, index=user_item_matrix.columns, columns=user_item_matrix.columns)

# ==============================
# 4️⃣ CF prediction functions
# ==============================
USER_WEIGHT = 4.5 / (4.5 + 5.5)
ITEM_WEIGHT = 5.5 / (4.5 + 5.5)
ALPHA = 0.5  # CB vs CF

def predict_user_based(user_id, movie_id, top_k=50):
    if user_id not in user_item_matrix.index or movie_id not in user_item_matrix.columns:
        return np.nan
    sims = user_sim.loc[user_id].values
    ratings = user_item_matrix[movie_id].values
    mask = ratings > 0
    if mask.sum() == 0:
        return np.nan
    sims = sims[mask]
    ratings = ratings[mask]
    if len(sims) > top_k:
        idx = np.argsort(sims)[-top_k:]
        sims = sims[idx]
        ratings = ratings[idx]
    if sims.sum() == 0:
        return np.nan
    return np.dot(sims, ratings) / sims.sum()

def predict_item_based(user_id, movie_id, top_k=50):
    if user_id not in user_item_matrix.index or movie_id not in user_item_matrix.columns:
        return np.nan
    sims = item_sim[movie_id].values
    ratings = user_item_matrix.loc[user_id].values
    mask = ratings > 0
    if mask.sum() == 0:
        return np.nan
    sims = sims[mask]
    ratings = ratings[mask]
    if len(sims) > top_k:
        idx = np.argsort(sims)[-top_k:]
        sims = sims[idx]
        ratings = ratings[idx]
    if sims.sum() == 0:
        return np.nan
    return np.dot(sims, ratings) / sims.sum()

# ==============================
# 5️⃣ Hybrid recommendation function
# ==============================
def recommend_hybrid(user_id, top_n=10):
    if user_id in user_item_matrix.index:
        user_history = user_item_matrix.loc[user_id]
        user_history = user_history[user_history > 0].to_dict()
    else:
        user_history = {}

    # 1️⃣ Content-Based scores
    cb_scores = np.zeros(len(movie_ids))
    for mid, rating in user_history.items():
        if mid not in movieid_to_index:
            continue
        idx = movieid_to_index[mid]
        cb_scores += cb_sim_matrix[idx] * rating
    if np.max(cb_scores) > 0:
        cb_scores = normalize(cb_scores.reshape(1, -1))[0]

    # 2️⃣ Collaborative Filtering scores
    cf_scores = np.zeros(len(movie_ids))
    for i, mid in enumerate(movie_ids):
        if mid in user_history:
            cf_scores[i] = 0
        else:
            user_pred = predict_user_based(user_id, mid)
            item_pred = predict_item_based(user_id, mid)
            user_pred = 0 if np.isnan(user_pred) else user_pred
            item_pred = 0 if np.isnan(item_pred) else item_pred
            cf_scores[i] = USER_WEIGHT * user_pred + ITEM_WEIGHT * item_pred
    if np.max(cf_scores) > 0:
        cf_scores = normalize(cf_scores.reshape(1, -1))[0]

    # 3️⃣ Hybrid CB + CF
    hybrid_scores = ALPHA * cb_scores + (1 - ALPHA) * cf_scores
    top_idx = np.argsort(hybrid_scores)[::-1][:top_n]
    return [movie_ids[i] for i in top_idx]

# ==============================
# 6️⃣ Precompute top-10 hybrid for 100 users
# ==============================
example_users = user_item_matrix.index[:100]  # chọn 100 users đầu
top_n = 10
scores_100_users = {}
for user_id in tqdm(example_users):
    scores_100_users[user_id] = recommend_hybrid(user_id, top_n=top_n)

with open("hybrid_scores_100_users.pkl", "wb") as f:
    pickle.dump(scores_100_users, f)
print("✔️ Saved top-10 hybrid scores for 100 users!")

# ==============================
# 7️⃣ Load & show recommendations
# ==============================
with open("hybrid_scores_100_users.pkl", "rb") as f:
    hybrid_scores_dict = pickle.load(f)

# ví dụ user đầu tiên
example_user = example_users[0]
top_10_movies = hybrid_scores_dict[example_user]
recommended_titles = movie_vecs_df.set_index('ID').loc[top_10_movies, 'Title'].tolist()

print(f"\nTop 10 recommended movies for user {example_user}:")
for i, title in enumerate(recommended_titles, 1):
    print(f"{i}. {title}")

100%|██████████| 100/100 [01:08<00:00,  1.46it/s]

✔️ Saved top-10 hybrid scores for 100 users!

Top 10 recommended movies for user 1:
1. Toy Story 2 (1999)
2. Cinema Paradiso (1988)
3. Forrest Gump (1994)
4. Stand by Me (1986)
5. After Life (1998)
6. Lion King, The (1994)
7. American Beauty (1999)
8. Kicking and Screaming (1995)
9. Little Mermaid, The (1989)
10. Sleeping Beauty (1959)

In [ ]:

with open("hybrid_scores_100_users.pkl", "rb") as f:
    hybrid_scores_dict = pickle.load(f)

example_user = example_users[1]
top_10_movies = hybrid_scores_dict[example_user]
recommended_titles = movie_vecs_df.set_index('ID').loc[top_10_movies, 'Title'].tolist()

print(f"\nTop 10 recommended movies for user {example_user}:")
for i, title in enumerate(recommended_titles, 1):
    print(f"{i}. {title}")

Top 10 recommended movies for user 2:
1. Forrest Gump (1994)
2. Godfather, The (1972)
3. Cinema Paradiso (1988)
4. Deliverance (1972)
5. Killing Fields, The (1984)
6. Schindler's List (1993)
7. Deer Hunter, The (1978)
8. Good Will Hunting (1997)
9. Shawshank Redemption, The (1994)
10. Field of Dreams (1989)